//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ica.StackIt.Application.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ica.StackIt.Application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;Ingress&quot;: [
        ///		{
        ///			&quot;Type&quot;: &quot;RDP&quot;,
        ///			&quot;Protocol&quot;: &quot;TCP&quot;,
        ///			&quot;Port&quot;: &quot;3389&quot;,
        ///			&quot;Source&quot;: &quot;207.65.232.226/32&quot;
        ///		},
        ///		{
        ///			&quot;Type&quot;: &quot;RDP&quot;,
        ///			&quot;Protocol&quot;: &quot;TCP&quot;,
        ///			&quot;Port&quot;: &quot;3389&quot;,
        ///			&quot;Source&quot;: &quot;207.65.237.90/32&quot;
        ///		},
        ///		{
        ///			&quot;Type&quot;: &quot;RDP&quot;,
        ///			&quot;Protocol&quot;: &quot;TCP&quot;,
        ///			&quot;Port&quot;: &quot;3389&quot;,
        ///			&quot;Source&quot;: &quot;207.65.232.225/32&quot;
        ///		},
        ///		{
        ///			&quot;Type&quot;: &quot;SSH&quot;,
        ///			&quot;Protocol&quot;: &quot;TCP&quot;,
        ///			&quot;Port&quot;: &quot;22&quot;,
        ///			&quot;Source&quot;: &quot;207.65.232.226/32&quot;
        ///		},
        ///		{
        ///			&quot;Type&quot;: &quot;SSH&quot;,
        ///			&quot;Protocol&quot;: &quot;TCP&quot;,
        ///			&quot;Port&quot;: &quot;22&quot;,
        ///			&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultSecurityGroupAddresses {
            get {
                return ResourceManager.GetString("DefaultSecurityGroupAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var getCidrs = function(port) {
        ///	if (port.External) {
        ///		return [&quot;0.0.0.0/0&quot;];
        ///	} else {
        ///		return [
        ///			&quot;10.0.0.0/8&quot;,
        ///			&quot;172.16.0.0/12&quot;,
        ///			&quot;192.168.0.0/16&quot;
        ///		];
        ///	}
        ///};
        ///
        ///var getProtocols = function(port) {
        ///	var protocols = [];
        ///	if (port.Tcp) {
        ///		protocols.push(&quot;tcp&quot;);
        ///	}
        ///	if (port.Udp) {
        ///		protocols.push(&quot;udp&quot;);
        ///	}
        ///
        ///	return protocols;
        ///};
        ///
        ///var getUserData = function(instance, instanceIndex, stackConfiguration, platform, hostName) {
        ///	if (platform !== &quot;windows&quot;) {
        ///		return getLinuxUserD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenerateCloudFormationTemplate {
            get {
                return ResourceManager.GetString("GenerateCloudFormationTemplate", resourceCulture);
            }
        }
    }
}
